version: '2'

services:

### Applications Code Container #############################

    applications:
      container_name: NOVALY_APPLICATIONS
      image: tianon/true
      volumes:
        - ${APPLICATION}:/var/www
      networks:
        backend:
          ipv4_address: 172.20.0.23

### Workspace Utilities Container ###########################

    workspace:
      container_name: NOVALY_WORKSPACE
      build:
        context: ./workspace
        args:
          - INSTALL_XDEBUG=${WORKSPACE_INSTALL_XDEBUG}
          - INSTALL_SOAP=${WORKSPACE_INSTALL_SOAP}
          - INSTALL_PHPREDIS=${WORKSPACE_INSTALL_PHPREDIS}
          - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
          - INSTALL_YARN=${WORKSPACE_INSTALL_YARN}
          - INSTALL_DRUSH=${WORKSPACE_INSTALL_DRUSH}
          - INSTALL_DRUPAL_CONSOLE=${WORKSPACE_INSTALL_DRUPAL_CONSOLE}
          - INSTALL_V8JS=${WORKSPACE_INSTALL_V8JS}
          - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL}
          - INSTALL_WORKSPACE_SSH=${WORKSPACE_INSTALL_WORKSPACE_SSH}
          - INSTALL_LARAVEL_ENVOY=${WORKSPACE_INSTALL_LARAVEL_ENVOY}
          - INSTALL_LARAVEL_INSTALLER=${WORKSPACE_INSTALL_LARAVEL_INSTALLER}
          - INSTALL_DEPLOYER=${WORKSPACE_INSTALL_DEPLOYER}
          - INSTALL_LINUXBREW=${WORKSPACE_INSTALL_LINUXBREW}
          - INSTALL_MC=${WORKSPACE_INSTALL_MC}
          - INSTALL_SYMFONY=${WORKSPACE_INSTALL_SYMFONY}
          - INSTALL_PYTHON=${WORKSPACE_INSTALL_PYTHON}
          - INSTALL_IMAGE_OPTIMIZERS=${WORKSPACE_INSTALL_IMAGE_OPTIMIZERS}
          - INSTALL_IMAGEMAGICK=${WORKSPACE_INSTALL_IMAGEMAGICK}
          - INSTALL_TERRAFORM=${WORKSPACE_INSTALL_TERRAFORM}
          - PUID=${WORKSPACE_PUID}
          - PGID=${WORKSPACE_PGID}
          - NODE_VERSION=${WORKSPACE_NODE_VERSION}
          - YARN_VERSION=${WORKSPACE_YARN_VERSION}
          - TZ=${WORKSPACE_TIMEZONE}
        dockerfile: "Dockerfile-${PHP_VERSION}"
      volumes_from:
        - applications
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        - "novaly.dev:172.20.0.24"
        - "adminer.dev:172.20.0.24"
      ports:
        - "${WORKSPACE_SSH_PORT}:22"
        - "35729:35729"
        - "3000:3000"
      tty: true
      networks:
        backend:
          ipv4_address: 172.20.0.22

### PHP-FPM Container #######################################

    php-fpm:
      container_name: NOVALY_PHP-FPM
      build:
        context: ./php-fpm
        args:
          - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
          - INSTALL_SOAP=${PHP_FPM_INSTALL_SOAP}
          - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
          - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
          - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
          - INSTALL_MEMCACHED=${PHP_FPM_INSTALL_MEMCACHED}
          - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
          - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
          - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
          - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
          - INSTALL_GHOSTSCRIPT=${PHP_FPM_INSTALL_GHOSTSCRIPT}
          - INSTALL_LDAP=${PHP_FPM_INSTALL_LDAP}
          - INSTALL_SWOOLE=${PHP_FPM_INSTALL_SWOOLE}
          - INSTALL_IMAGE_OPTIMIZERS=${PHP_FPM_INSTALL_IMAGE_OPTIMIZERS}
          - INSTALL_IMAGEMAGICK=${PHP_FPM_INSTALL_IMAGEMAGICK}
        dockerfile: "Dockerfile-${PHP_VERSION}"
      volumes_from:
        - applications
      volumes:
        - ./php-fpm/php${PHP_VERSION}.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
        - "80"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        - "novaly.dev:172.20.0.24"
        - "adminer.dev:172.20.0.24"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      networks:
        backend:
          ipv4_address: 172.20.0.21

### NGINX Server Container ##################################

    nginx:
      container_name: NOVALY_NGINX
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
      volumes_from:
        - applications
      volumes:
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80"
        - "${NGINX_HOST_HTTPS_PORT}:443"
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        - "novaly.dev:172.20.0.24"
        - "adminer.dev:172.20.0.24"
      depends_on:
        - php-fpm
      networks:
        backend:
          ipv4_address: 172.20.0.24

### MySQL Container #########################################

    mysql:
      container_name: NOVALY_DATABASE
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - TZ=${WORKSPACE_TIMEZONE}
      volumes:
        - ../database/novaly:/var/lib/mysql:delegated
      ports:
        - "${MYSQL_PORT}:3306"
      expose:
        - "3306"
      restart: always
      networks:
        backend:
          ipv4_address: 172.20.0.20
      command: mysqld --innodb-buffer-pool-size=4003987456

### Redis Container #########################################

    redis:
      container_name: NOVALY_REDIS
      build: ./redis
      volumes:
        - ${DATA_SAVE_PATH}/redis:/data
      ports:
        - "${REDIS_PORT}:6379"
      networks:
        backend:
          ipv4_address: 172.20.0.19

### Adminer Container ####################################

    adminer:
      container_name: NOVALY_ADMINER
      image: adminer:latest
      ports:
        - "${ADM_PORT}:8080"
      depends_on:
        - php-fpm
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
        - "novaly.dev:172.20.0.24"
        - "adminer.dev:172.20.0.24"
      networks:
        backend:
          ipv4_address: 172.20.0.18

### Jenkins ###################################################

    # jenkins:
    #   container_name: NOVALY_JENKINS
    #   build: ./jenkins
    #   environment:
    #     JAVA_OPTS: "-Djava.awt.headless=true"
    #   ports:
    #     - "${JENKINS_HOST_SLAVE_AGENT_PORT}:50000"
    #     - "${JENKINS_HOST_HTTP_PORT}:8080"
    #   privileged: true
    #   volumes:
    #     - ${JENKINS_HOME}:/var/jenkins_home
    #     - /var/run/docker.sock:/var/run/docker.sock
    #   networks:
    #     - backend

### Networks Setup ############################################

networks:
  backend:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
          gateway: "172.20.0.1"

### Volumes Setup #############################################

volumes:
  mysql:
    driver: "local"
  redis:
    driver: "local"
  adminer:
    driver: "local"
